### ISSUE TITLE
Fixed length packet tagger

### ISSUE THREAD

**Issue by dernasherbrezon** [daniestevez/gr-aausat#1]
Good day! 

I'm trying to understand aausat-4.grc. 

Could you please help me?

I'm wondering why did you put "Fixed Length Packet Tagger" block? Packet size is predefined (http://www.space.aau.dk/aausat4/index.php?n=Main.Ham) and not 2008 bytes long..

**Comment by daniestevez** [comment]
The packet size is variable (there are two possible sizes if I recall correctly), but there is a maximum packet size. "Fixed Length Packet Tagger" gets a 2008 bit (not byte) chunk, which is long enough to guarantee that the full packet is contained in this chunk.

PS: Please use Github issues only to report issues. I can be reached through email (or other means) to discuss other matters.
